$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        375:{
            items:1
        },
        425:{
            items:2
        },
        768:{
            items:3
        },
        1024:{
            items:4
        },
        1440:{
            items:5
        }
    }
})